### PR TITLE
upgrade mysql 5.6 to 5.7 for integration tests

### PR DESCRIPTION
**Pull request by phillipedwards**
Upgrade `quickstart-docker-compose` mysql version from 5.6 to 5.7.

### CODE REVIEW

**Comment by phillipedwards** [comment]
Included ecs-hosted upgrade of 5.6-5.7 as those have been tested.

**Comment by EvanBoyle** [comment]
@phillipedwards are you planning on merging this?

**Comment by phillipedwards** [comment]
@EvanBoyle Yes, I should have already. Can you take a look and review?

**Review by EvanBoyle — APPROVED** [review]
Looks good to me! 

Would you be willing to open a follow up PR trying this out with MySQL 8.0? 

It would be nice to be able to advertise that support now that we've landed 5.7. @kmosher is planning on migrating the service to 8.0 in November.

**Comment by phillipedwards** [comment]
Yeah, I'd be happy to pick this back up when we're ready to test out mysql 8.

**Pull request merged**
